In [1]:
#Import Libraries
import pandas as pd
import requests
import io

In [2]:
# Downloading the csv file from the GitHub account
url = "https://raw.githubusercontent.com/bgpayne23/mirahealth/main/datasets/mira_data_one_hot.csv" # Make sure the url is the raw version of the file on GitHub
download = requests.get(url).content
# Reading the downloaded content and turning it into a pandas dataframe
df = pd.read_csv(io.StringIO(download.decode('utf-8')))
# Printing out the first 5 rows of the dataframe
df.drop('Unnamed: 0', inplace=True, axis=1)
df

,obgyn_AvgPatientTime,obgyn_NumOfPatients,obgyn_QualityRisk,obgyn_TotalHours,obgyn_BurnoutRisk,Age,SystolicBP,DiastolicBP,BS,BodyTemp,...,Payer_Private,Payer_Public,Payer_Uninsured,Location_Metropolitan,Location_Micropolitan,Location_Rural,Income_Q1,Income_Q2,Income_Q3,Income_Q4
0,21,16,0,336,0,18,120,90,6.1,98.0,...,0,0,1,0,0,1,0,0,0,1
1,11,30,1,330,0,17,120,80,7.5,98.0,...,0,1,0,0,0,1,0,0,1,0
2,13,18,1,234,0,20,120,80,6.9,102.0,...,1,0,0,1,0,0,0,0,0,1
3,13,21,1,273,0,31,140,95,19.0,98.0,...,0,1,0,0,0,1,0,1,0,0
4,14,26,0,364,1,20,120,85,15.0,98.0,...,0,1,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2257,18,27,0,486,1,17,120,90,15.0,98.0,...,0,1,0,1,0,0,1,0,0,0
2258,18,23,0,414,1,38,120,80,11.0,98.0,...,0,0,1,1,0,0,0,0,0,1
2259,11,30,1,330,0,36,120,95,11.0,98.0,...,0,1,0,0,0,1,0,0,0,1
2260,21,16,0,336,0,39,100,65,7.5,98.0,...,1,0,0,1,0,0,0,0,0,1
2261,9,22,1,198,0,21,120,90,6.9,98.0,...,0,1,0,1,0,0,0,0,0,1

In [3]:
#split dataset in features and target variable
feature_cols = df.columns.values.tolist()
feature_cols.remove('HDP')
X = df[feature_cols] # Features
y = df.HDP # Target variable

In [4]:
# split X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=16)

In [7]:
# import the class
from sklearn.linear_model import LogisticRegression
# instantiate the model (using the default parameters)
logreg = LogisticRegression()
# fit the model with data
logreg.fit(X_train, y_train)

NameError: name 'max_iter' is not defined

In [6]:
#Score the Accuracy of the model
from sklearn.metrics import accuracy_score
y_pred = logreg.predict(X_test)
score =accuracy_score(y_test,y_pred)
print('Test Accuracy Score: ', score)

Test Accuracy Score:  0.8869257950530035